baseURL = "https://svennekula.netlify.app/"
title = "Sven Nekula"
theme = "hugo-theme-m10c"
paginate = 5
avatar = "C:\\Users\\svenn\\Documents\\Documents\\GitHub\\blog\\procrastination\\themes\\hugo-theme-m10c\\static\\avatar.jpg"
[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"

[params]
  author = "Sven Nekula"
  description = "Welcome to my personal blog!"
  menu_item_separator = " - "
  [[params.social]]
    name = "github"
    url = "https://github.com/SvenNekula"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/NekulaSven"

  # Brown theme
  #[params.style]
  #  darkestColor = "#463625"
  #  darkColor = "#2a3738"
  #  primaryColor = "#eeee6a"
  #  lightColor = "#96a879"
  #  lightestColor = "#ffffff"

  # Green theme
  #[params.style]
  #  darkestColor = "#315659"
  #  darkColor = "#253031"
  #  primaryColor = "#dad865"
  #  lightColor = "#96a879"
  #  lightestColor = "#fff"

  # Red and black theme
  #[params.style]
  #  darkestColor = "#d35050"
  #  darkColor = "#212121"
  #  primaryColor = "#ffffff"
  #  lightColor = "#a2a2a2"
  #  lightestColor = "#d3d3d3"
