---
title: "Introductory post!"
author: "Sven Nekula"
date: 2021-01-06
categories: ["R"]
tags: ["Introduction"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE)
```

# Who am I?

My name is Sven Nekula, I'm 23 years old and I graduated from the Friedrich-Alexander-
University in the summer of 2020 with a Bachelor of Arts in Economics and Sociology.
Since November 2020 I've been studying Survey Statistics at the Otto-Friedrich-University in Bamberg. 
The first time I came into contact with statistics was in the third semester of my
bachelor studies. I quickly realized, that I enjoyed statistics the most out of all
my classes and thus decided to attend more and more classes that dealt with statistics.
In the fourth semester I took classes that taught the use of SPSS and R and I've worked 
with R ever since. In my fifth and sixth semester I came across GitHub and rmarkdown
and created two small websites that you can see on my GitHub profile. 

# Why did I create this blog?

I created this blog for multiple reasons:


* to further develope my skills with R, GitHub and whatever else I'm going to be using
down the line
* to be accountable and learn more by doing
* and finally to 'productively procrastinate' as Rebecca Barter put it in her [blog](http://www.rebeccabarter.com/blog/2020-02-03_blogger/){target="_blank"}
that ultimately motivated me to start all of this. 

# What will I post here?

I will post different projects on here. Those will range from personal projects to university
tasks. I'm also really interested in learning more about machine learning, so expect a
machine learning project soon. 


Even though I'll try to post here weekly, I can't promise that it will always be the case.

Especially during february-march resp. july-august I'm probably swamped due to university
assignments and exams, but I will try my best.

I think that's all I have to say right now. See you next time! -SN